KEYWORDS = [
    'paternity',
    'maternity',
    'gay', 
    'gays', 
    'lesbian', 
    'lesbians', 
    'lgbt', 
    'lgbtq',
    'male',
    'mother',
    'mothers',
    'mansplain',
    'minority',
    'muslim',
    'female',
    'father',
    'fathers',
    'race',
    'latino',
    'latinx',
    'latinos',
    'hispanic',
    'hispanics',
    'minorities',
    'atheist',
    'agnostic',
    'asexual',
    'ally',
    'asian',
#    'asian man',
#    'asian men',
    'asians',
    'african',
    'african-american',
#    'african man',
#    'african men', 
#    'african woman',
#    'african women'
    'africans',
    'aapi',
    'ageism',
    'allship',
    'bme',
    'bame',
    'bisexsual',
    'bisexsuals',
    'black',
    'blacks',
    'buddhist',
#    'black man',
#    'black men',
#    'black woman',
#    'black women',
#    'culture',
    'cisgender',
    'christian',
    'hindu',
#    'corporate social responsibility',
#    'conscious prejudice',
#    'creative abrasion',
#    'culture fit',
    'dei',
    'diaspora',
    'disability',
    'discrimination',
    'diversity',
    'diversify',
    'disability',
#    'disable people',
    'discrimination',
    'jew',
    'jews',
    'jewish',
#    'jewish man',
#    'jewish men',
#    'jewish woman',
#    'jewish women',
    'homophobism',
    'homophobic',
    'harassment',
    'homosexual',
    'homosexuals',
    #'workplace inclusion',
    'non-binary',
    'transgender',
    'transgenders',
    'transsexual',
    'queer',
    'queers',
    'intersex',
    'equality',
#    'emotional tax',
#    'employee resource group',
#    'ethnic group',
    'equality',
    'femme',
    'gender',
    'dysphoria',
#    'gender dysphoria',
#    'gender expression',
#    'gender identity',
#    'gender privilege',
    'genderqueer',
    'groupthink',
    'gsd',
    #'gender reassignment',
    'hepeating',
    'heterosexual',
    #'heterosexual privilege',
    'homophobia',
    'heterosexual',
    'islamophobic',
    'inclusion',
#    'inclusive culture',
#    'inclusive leader',
#    'innate diversity',
    'intersectionality',
    'intersex',
    'lgbtqi',
    'lgbtqia',
#    'people of color',
    'prejudice',
    'privilege',
    'pansexual',
    'races',
    'racism',
    'racist',
    'racists',
    #'sexual discrimination',
    'sikh',
    'sexist',
    #'skin color',
    'sex', 
    'orientation',
    #'sex orientation',
    'stereotype',
    'stereotypes',
    'transphobia',
    'transsexual',
#    'underrepresented groups',
#    'white privilege',
#    'white supremacy',
    'xenophobia'
#    'workplace inclusion',
#    'zero sum game'
    ]
